"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";

const pressLogos = [
  { src: "/bloomberg-pr.png", alt: "Bloomberg" },
  { src: "/yahoo-pr.png", alt: "Yahoo!" },
  { src: "/marketwatch-pr.png", alt: "MarketWatch" },
  { src: "/businessinsider-pr.png", alt: "Business Insider" },
  { src: "/asiaone-pr.png", alt: "AsiaOne" },
  { src: "/digitaljournal-pr.png", alt: "Digital Journal" },
];

const steps = [
  { num: "01", title: "Register & Get Started", desc: "Set up your advertiser account, complete the verification process, and access your partner dashboard. Many brands launch their first campaigns within 48 hours." },
  { num: "02", title: "Design Your Campaigns", desc: "Configure your campaigns with the desired commission model (CPA, CPS, CPL, or hybrid). Set tracking links, limits, and payouts tailored to your business objectives." },
  { num: "03", title: "Partner with Publishers", desc: "Tap into our carefully vetted publisher network. Approve the partners that align with your niche and begin driving high-quality, targeted traffic." },
  { num: "04", title: "Monitor, Refine & Grow", desc: "Leverage real-time analytics to track clicks, conversions, and ROI. Fine-tune your campaigns and expand with your highest-performing publishers." },
];

const programTypes = [
  { title: "CPA (Cost Per Action)", desc: "Pay solely when a user completes a specific action—such as a sale, lead, registration, or download. Perfect for campaigns focused on measurable results." },
  { title: "CPS (Cost Per Sale)", desc: "Earn a commission for each sale generated by a publisher. This model is widely used for e-commerce and direct-response campaigns." },
  { title: "CPL (Cost Per Lead)", desc: "Compensate for each verified lead. Ideal for B2B, insurance, finance, and other industries where lead quality is essential." },
  { title: "CPI (Cost Per Install)", desc: "Pay only when a user installs your app or starts a software trial. Best suited for mobile apps, SaaS platforms, and trial-based offers." },
  { title: "Revenue Share", desc: "Reward publishers with a percentage of the revenue generated from referred customers. Ideal for subscription-based businesses and models focused on long-term customer value." },
  { title: "Hybrid & Tailored Models", desc: "Mix different commission structures or create custom payout rules. We support tiered incentives, performance bonuses, and seasonal campaign setups." },
];

const industries = [
  { title: "Online Retail & E-commerce", desc: "Boost product sales through partnerships with coupon platforms, content publishers, and product comparison websites." },
  { title: "Finance & Insurance", desc: "Generate high-quality leads through comparison platforms and review publishers, backed by strong compliance support throughout the process." },
  { title: "SaaS & Software", desc: "Drive trial registrations and subscription growth through partnerships with tech content creators and B2B-focused publishers." },
  { title: "Travel & Hospitality", desc: "Increase bookings and package sales by partnering with travel-focused affiliates, publishers, and influencers." },
  { title: "Health & Wellness", desc: "Grow supplement, fitness, and wellness brands through trusted publisher partnerships built with compliance in mind." },
  { title: "Education & Online Learning", desc: "Drive student enrollments and course sales by partnering with education-focused and lifestyle publishers." },
];

const whyChoose = [
  { title: "Next-Level Partnerships", desc: "Engage your audience worldwide using our extensive partner network and a variety of marketing channels." },
  { title: "Product-Focused Search", desc: "Publishers promote your products with detailed ads that attract highly qualified traffic to your website." },
  { title: "Social Reach", desc: "Leverage creators and influencers to engage their audience, paying only for measurable results." },
  { title: "Performance Dashboard", desc: "Gain complete insights into campaign performance and ROI, allowing you to optimize strategies and scale effectively." },
];

const differentiators = [
  { title: "Easy to Use", desc: "Our platform is intuitive, making setup and onboarding simple for every user." },
  { title: "Budget-Friendly", desc: "Pay commissions only when a sale or desired action is completed." },
  { title: "Trusted Partners", desc: "Access a network of high-quality publishers and reliable performance data." },
  { title: "Insightful Monitoring", desc: "Track campaign performance with detailed reports and analytics." },
  { title: "Dedicated Support", desc: "Work closely with experienced relationship managers to maximize results." },
  { title: "Continuous Optimization", desc: "Refine campaigns using in-depth reporting and actionable insights." },
];

const faqs = [
  { q: "1. What is LinkHexa for Advertisers?", a: "LinkHexa is a performance-driven affiliate network that connects brands with trusted publishers. Advertisers can grow their audience, increase sales, and only pay for measurable results." },
  { q: "2. How do I get started with LinkHexa?", a: "Getting started is simple. Sign up, create your campaigns with your preferred commission model, connect with publishers, and start tracking results in real time." },
  { q: "3. What types of campaigns can I run?", a: "We support a variety of models, including CPA, CPS, CPL, CPI, revenue share, and hybrid campaigns—giving you flexibility to match your business objectives." },
  { q: "4. How do I track campaign performance?", a: "Our platform provides live reporting for clicks, conversions, and ROI. You can monitor performance by campaign or publisher, optimize offers, and make data-driven decisions instantly." },
  { q: "5. How does LinkHexa ensure traffic quality?", a: "We use advanced fraud detection and traffic monitoring systems. This protects your campaigns from invalid clicks, fraudulent conversions, and ensures you only pay for genuine results." },
];

export default function AdvertisersContent() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  return (
    <>
      <Navbar />
      <main className="min-h-screen">
        {/* Hero */}
        <section className="relative overflow-hidden pt-24 pb-16 sm:pt-28 sm:pb-20 lg:pb-24">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute left-1/4 top-1/4 h-[400px] w-[400px] rounded-full bg-indigo-500/20 blur-[120px]" />
            <div className="absolute right-1/4 top-1/2 h-[350px] w-[350px] rounded-full bg-violet-500/15 blur-[100px]" />
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_50%_at_50%_-20%,rgba(99,102,241,0.12),transparent)]" />
          </div>
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="grid items-center gap-10 lg:grid-cols-2 lg:gap-12">
              <div>
                <motion.p initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="text-sm font-medium uppercase tracking-widest text-indigo-400">For Brands & Merchants</motion.p>
                <motion.h1 initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="mt-4 text-3xl font-bold tracking-tight text-white sm:text-4xl lg:text-5xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>Scale Your Business with the Right Partners</motion.h1>
                <motion.p initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="mt-4 max-w-xl text-base text-zinc-400 sm:text-lg">Not on LinkHexa yet? Unlock growth by connecting with high-quality publishers, pay strictly for results, and monitor every conversion in real time.</motion.p>
                <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="mt-8 flex flex-wrap gap-4">
                  <Link href="/get-started" className="rounded-lg bg-indigo-600 px-6 py-3.5 font-semibold text-white transition-colors hover:bg-indigo-500">Get started as advertiser</Link>
                </motion.div>
                <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="mt-10 grid grid-cols-3 gap-4">
                  {["80%", "90%", "99%"].map((val, i) => (
                    <div key={i} className="rounded-xl border border-white/10 bg-zinc-900/60 px-4 py-3 text-center">
                      <p className="text-2xl font-bold text-indigo-400 sm:text-3xl">{val}</p>
                      <p className="mt-0.5 text-xs text-zinc-500">{i === 0 ? "Sales lift" : i === 1 ? "Traffic" : "Uptime"}</p>
                    </div>
                  ))}
                </motion.div>
              </div>
              <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.3 }} className="relative">
                <div className="relative overflow-hidden rounded-2xl border border-white/10 shadow-2xl">
                  <Image src="/meeting-background-o9k6b5wkuevvy1f7.jpg" alt="Team collaboration" width={600} height={400} className="aspect-[3/2] w-full object-cover" priority sizes="(max-width: 1024px) 100vw, 50vw" />
                </div>
              </motion.div>
            </div>
          </div>
        </section>

        {/* As seen on */}
        <section className="border-y border-white/10 bg-zinc-800/60 py-6 sm:py-8">
          <p className="mb-4 text-center text-xs font-semibold uppercase tracking-widest text-indigo-400">As seen on</p>
          <div className="flex flex-wrap items-center justify-center gap-6 sm:gap-10">
            {pressLogos.map((logo) => (
              <div key={logo.alt} className="flex h-8 w-24 items-center justify-center opacity-80 sm:h-9 sm:w-28">
                <Image src={logo.src} alt={logo.alt} width={112} height={36} className="h-full w-full object-contain" />
              </div>
            ))}
          </div>
        </section>

        {/* Millions of opportunities */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute -right-32 top-1/4 h-[350px] w-[350px] rounded-full bg-indigo-500/15 blur-[100px]" />
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_50%_80%_at_0%_50%,rgba(99,102,241,0.08),transparent)]" />
          </div>
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="grid items-center gap-10 lg:grid-cols-2 lg:gap-14">
              <div className="relative order-2 lg:order-1">
                <div className="overflow-hidden rounded-2xl border border-white/10 shadow-xl">
                  <Image src="/639b7845e9be869771e540b8_mural-blog-images.jpg" alt="Data and analytics" width={560} height={380} className="aspect-[4/3] w-full object-cover" sizes="(max-width: 1024px) 100vw, 50vw" />
                </div>
              </div>
              <div className="order-1 lg:order-2">
                <h2 className="text-2xl font-bold tracking-tight text-white sm:text-3xl lg:text-4xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>Unlock Millions of Growth Opportunities</h2>
                <p className="mt-4 text-zinc-400">LinkHexa makes it simple to get started while providing industry expertise and actionable insights. Expand with a partner network designed for measurable performance.</p>
                <p className="mt-4 text-zinc-400">Whether you’re an emerging D2C brand or a well-established retailer, our platform connects you with new audiences without any upfront ad spend. You only scale when results are delivered.</p>
                <ul className="mt-6 space-y-3">
                  {["High-quality traffic from carefully vetted publishers", "Instant reporting and conversion tracking", "Optimize campaigns and grow with top-performing partners", "Cost-efficient: pay commissions only when conversions occur"].map((item, i) => (
                    <li key={i} className="flex items-center gap-3 text-sm text-zinc-300">
                      <span className="h-2 w-2 shrink-0 rounded-full bg-indigo-400" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* How it works */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute -left-32 top-1/3 h-[350px] w-[350px] rounded-full bg-violet-500/15 blur-[100px]" />
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_50%_80%_at_100%_50%,rgba(99,102,241,0.08),transparent)]" />
          </div>
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <p className="text-center text-sm font-medium uppercase tracking-widest text-indigo-400">Easy & Streamlined</p>
            <h2 className="mt-4 text-center text-2xl font-bold tracking-tight text-white sm:text-3xl lg:text-4xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>How Advertisers Get Started</h2>
            <p className="mx-auto mt-3 max-w-2xl text-center text-zinc-400">Grow your business in four simple steps—from registration to scaling campaigns with measurable results.</p>
            <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              {steps.map((step, i) => (
                <motion.div key={step.num} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.08 }} className="rounded-2xl border border-white/10 bg-zinc-900/60 p-6">
                  <span className="text-2xl font-bold text-indigo-400">{step.num}</span>
                  <h3 className="mt-3 font-semibold text-white">{step.title}</h3>
                  <p className="mt-2 text-sm text-zinc-400">{step.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Program types */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute left-1/2 top-1/4 h-[300px] w-[300px] -translate-x-1/2 rounded-full bg-indigo-500/10 blur-[100px]" />
          </div>
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <p className="text-center text-sm font-medium uppercase tracking-widest text-indigo-400">Flexible Partnership Models</p>
            <h2 className="mt-4 text-center text-2xl font-bold tracking-tight text-white sm:text-3xl lg:text-4xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>Supported Program Types</h2>
            <p className="mx-auto mt-3 max-w-2xl text-center text-zinc-400">Select the commission structure that best aligns with your business goals and marketing strategy.</p>
            <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {programTypes.map((item, i) => (
                <motion.div key={item.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="rounded-2xl border border-white/10 bg-zinc-900/60 p-5">
                  <h3 className="font-semibold text-white">{item.title}</h3>
                  <p className="mt-2 text-sm text-zinc-400">{item.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Industries */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute -right-32 top-1/3 h-[300px] w-[300px] rounded-full bg-violet-500/12 blur-[100px]" />
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_60%_60%_at_80%_20%,rgba(99,102,241,0.06),transparent)]" />
          </div>
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <p className="text-center text-sm font-medium uppercase tracking-widest text-indigo-400">Our Trusted Partners</p>
            <h2 className="mt-4 text-center text-2xl font-bold tracking-tight text-white sm:text-3xl lg:text-4xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>Industries We Support</h2>
            <p className="mx-auto mt-3 max-w-2xl text-center text-zinc-400">From e-commerce to SaaS, we help businesses across a wide range of industries grow customer acquisition through reliable publisher partnerships.</p>
            <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {industries.map((item, i) => (
                <motion.div key={item.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="rounded-2xl border border-white/10 bg-zinc-900/60 p-5">
                  <h3 className="font-semibold text-white">{item.title}</h3>
                  <p className="mt-2 text-sm text-zinc-400">{item.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* We deliver success - image left, stats right */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute -left-32 top-1/4 h-[350px] w-[350px] rounded-full bg-indigo-500/15 blur-[100px]" />
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_50%_80%_at_0%_50%,rgba(99,102,241,0.1),transparent)]" />
          </div>
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="grid items-center gap-10 lg:grid-cols-2 lg:gap-14">
              <motion.div initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="overflow-hidden rounded-2xl border border-white/10 shadow-xl">
                <Image src="/Happy-work-team-cheering-and-celebrating-at-meeting-team-collaboration.jpg" alt="Team delivering success" width={560} height={400} className="aspect-[4/3] w-full object-cover" sizes="(max-width: 1024px) 100vw, 50vw" />
              </motion.div>
              <div>
                <h2 className="text-2xl font-bold tracking-tight text-white sm:text-3xl lg:text-4xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>Driving Measurable Success</h2>
                <p className="mt-4 text-zinc-400">Connect with a vast network of affiliates and elevate your marketing with accurate tracking and dependable payouts.</p>
                <p className="mt-4 text-zinc-400">Our advertisers experience tangible growth in sales, traffic, and revenue by collaborating with the right publishers. We prioritize transparency and foster long-term, results-driven partnerships.</p>
                <div className="mt-8 grid grid-cols-3 gap-4">
                  {[
                    { val: "80%", label: "Increased sales" },
                    { val: "90%", label: "Increased traffic" },
                    { val: "99%", label: "Uptime" },
                  ].map((stat, i) => (
                    <div key={i} className="rounded-xl border border-white/10 bg-zinc-900/60 p-4 text-center">
                      <p className="text-2xl font-bold text-indigo-400 sm:text-3xl">{stat.val}</p>
                      <p className="mt-0.5 text-xs text-zinc-500">{stat.label}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Dare to make the right choice */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute right-0 top-1/3 h-[300px] w-[300px] rounded-full bg-violet-500/12 blur-[100px]" />
          </div>
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <h2 className="text-center text-2xl font-bold tracking-tight text-white sm:text-3xl lg:text-4xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>Choose Growth with Confidence</h2>
            <p className="mx-auto mt-3 max-w-2xl text-center text-zinc-400">Partner with trusted publishers and expand your affiliate program with precise tracking and reliable payouts.</p>
            <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              {whyChoose.map((item, i) => (
                <motion.div key={item.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="rounded-2xl border border-white/10 bg-zinc-900/60 p-6 text-center">
                  <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-500/20 text-indigo-400">
                    <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                  </div>
                  <h3 className="mt-4 font-semibold text-white">{item.title}</h3>
                  <p className="mt-2 text-sm text-zinc-400">{item.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* What makes us different - 6 grid with image section */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="absolute inset-0 bg-zinc-900/30" />
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute left-1/2 top-1/4 h-[300px] w-[300px] -translate-x-1/2 rounded-full bg-indigo-500/10 blur-[100px]" />
          </div>
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <h2 className="text-center text-2xl font-bold tracking-tight text-white sm:text-3xl lg:text-4xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>What makes us different?</h2>
            <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {differentiators.map((item, i) => (
                <motion.div key={item.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="rounded-2xl border border-white/10 bg-zinc-900/60 p-5">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-500/20 text-indigo-400">
                    <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                  </div>
                  <h3 className="mt-3 font-semibold text-white">{item.title}</h3>
                  <p className="mt-1 text-sm text-zinc-400">{item.desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Performance-first + image */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute -right-32 top-1/3 h-[350px] w-[350px] rounded-full bg-indigo-500/15 blur-[100px]" />
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_50%_80%_at_100%_50%,rgba(99,102,241,0.08),transparent)]" />
          </div>
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="grid items-center gap-10 lg:grid-cols-2 lg:gap-14">
              <div>
                <h2 className="text-2xl font-bold tracking-tight text-white sm:text-3xl lg:text-4xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>Results-Driven Marketing</h2>
                <p className="mt-4 text-lg font-medium text-indigo-400">Maximize ROI with no wasted ad spend.</p>
                <p className="mt-4 text-zinc-400">Unlike traditional CPM or CPC models, affiliate marketing ensures you pay only for actual results—whether a sale, lead, or app install—making every dollar count.</p>
                <p className="mt-4 text-zinc-400">Our platform provides complete transparency with real-time analytics: track clicks, conversions, and detailed performance per publisher and campaign. No hidden metrics—you see exactly where value comes from.</p>
                <ul className="mt-6 space-y-2 text-sm text-zinc-300">
                  {["Live tracking of clicks and conversions", "Detailed performance insights at the publisher level", "Advanced fraud prevention and traffic quality controls", "Flexible payment options and invoicing"].map((item, i) => (
                    <li key={i} className="flex items-center gap-2">
                      <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-indigo-400" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
              <motion.div initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="overflow-hidden rounded-2xl border border-white/10 shadow-xl">
                <Image src="/young-business-people-meeting-office-teamwork-group-success-corporate-discussion_565246-1628.avif" alt="Performance and reporting" width={560} height={380} className="aspect-[4/3] w-full object-cover" sizes="(max-width: 1024px) 100vw, 50vw" />
              </motion.div>
            </div>
          </div>
        </section>

        {/* Stats strip */}
        <section className="relative overflow-hidden py-12 sm:py-16">
          <div className="absolute inset-0 bg-zinc-900/50" />
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <p className="text-center text-sm font-medium uppercase tracking-widest text-indigo-400">Why advertisers trust us</p>
            <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
              {[
                { val: "30k+", label: "Active advertisers" },
                { val: "18,420+", label: "Live offers" },
                { val: "$5M+", label: "Annual affiliate revenue tracked" },
                { val: "30", label: "Avg. days to first conversion" },
              ].map((stat, i) => (
                <div key={i} className="rounded-2xl border border-white/10 bg-zinc-900/60 p-6 text-center">
                  <p className="text-3xl font-bold text-indigo-400">{stat.val}</p>
                  <p className="mt-1 text-sm text-zinc-500">{stat.label}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute left-1/2 top-1/3 h-[280px] w-[280px] -translate-x-1/2 rounded-full bg-indigo-500/10 blur-[100px]" />
          </div>
          <div className="relative mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
            <p className="text-center text-sm font-medium uppercase tracking-widest text-indigo-400">Support</p>
            <h2 className="mt-4 text-center text-2xl font-bold tracking-tight text-white sm:text-3xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>Frequently Asked Questions</h2>
            <div className="mt-10 space-y-3">
              {faqs.map((faq, i) => (
                <div key={i} className="rounded-xl border border-white/10 bg-zinc-900/40 overflow-hidden">
                  <button type="button" onClick={() => setOpenFaq(openFaq === i ? null : i)} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left">
                    <span className="font-semibold text-white">{faq.q}</span>
                    <span className={`shrink-0 text-indigo-400 transition-transform ${openFaq === i ? "rotate-180" : ""}`}>
                      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                    </span>
                  </button>
                  {openFaq === i && <div className="border-t border-white/5 px-5 py-4 text-sm text-zinc-400">{faq.a}</div>}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32">
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_50%_at_50%_120%,rgba(99,102,241,0.15),transparent)]" />
          </div>
          <div className="relative mx-auto max-w-3xl px-4 text-center sm:px-6 lg:px-8">
            <h2 className="text-2xl font-bold tracking-tight text-white sm:text-3xl lg:text-4xl" style={{ fontFamily: "var(--font-libre-baskerville), serif" }}>Kickstart Your Growth with Performance Marketing</h2>
            <p className="mt-4 text-zinc-400">Join a dynamic affiliate platform where advertisers, publishers, and creators collaborate to expand reach, boost results, and unlock new revenue opportunities.</p>
            <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
              <Link href="/get-started" className="rounded-lg bg-indigo-600 px-6 py-3.5 font-semibold text-white transition-colors hover:bg-indigo-500">Create Advertiser Account</Link>
              <Link href="/contact" className="rounded-lg border-2 border-white/20 bg-white/5 px-6 py-3.5 font-semibold text-white transition-colors hover:bg-white/10">Talk To Team</Link>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
